### ISSUE TITLE
Question/Remarque de François Van Hees

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/mycarenet#77]
Bart,

Bonjour,

J’ai eu un peu de retard pour mon intervention … et je n’ai pas pu participer à la réunion … Mais je viens d’avoir Karlien en ligne qui m’a conseillé de te recontacter … 

J’ai déjà parlé avec Philippe sur l’interpellation que j’ai faite liée à eAgreement et aux données de la prescription.   Mais j’aurais aimé t’en parler vu que je n’ai pas pu défendre ma position aujourd’hui.

1.	J’avais compris lors de notre dernière réunion que l’on ne communiquerai qu’uniquement les données de la référence de UMEHP dans les eAgreements et pas d’autres données.  J’avais donc compris que les OA iraient consulter les données supplémentaires nécessaires dans UMEHP … On parle ici pour les Kiné :
a.	La référence du prescripteur
b.	La date de prescription
c.	Le nombre de séances (obligatoire pour les kinés, inutiles pour la logo)
d.	(PDF)   
Plus potentiellement d’autres infos nécessaires mais non communiquées dans le message FHIR comme en kiné (« est-ce qu’une seconde séance par jour est  demandée par le prescripteur ? )

2.	J’entend que Philippe pour des raisons pragmatiques (que je comprend également) souhaite que cela soit les prestataires qui nous communiquent tout de même une partie de ces informations dans le message eAgreement.  Seul le PDF ne nous serait plus communiqués.  On aurait donc pour la proposition de Philippe, les données suivantes qui nous seraient communiquées 
a.	La référence du prescripteur
b.	La date de prescription
c.	Le nombre de séances (pour les kinés)
d.	(PDF)   
Mais les OA devraient toujours consulter UMEHP pour contrôler la validité de ces informations et pour obtenir les informations complémentaires non reprises dans le message FHIR 
(« est-ce qu’une seconde séance par jour est  demandée par le prescripteur ? )
Ne pas communiquer de pdf quand on travaille avec UMEHP e parait de toute façon logique, car si la prescription est électronnique par défaut il n’y a pas de pdf.  

Point de vue lisibilité du message, je comprend qu’on souhaite communiquer quelques informations complémentaires dans le message.  Mais je ne pense pas que cela soit une bonne option.
a.	Pour moi c’est une source d’erreur … Les logiciels kinés et logiciels logopédies devront eux à termes récupérer ces informations (électroniquement ou manuellement). En cas d’erreur, si les OA se basent sur cette information, cela peut engendrer une erreur d’interprétation au niveau des OAs.
b.	Cela crée une dépendance avec UMEHP de notre package (FHIR) en cas de changement ou de l’ajout d’autre domaines.   A priori, la référence du prescripteur et la date de prescription sont des données standard qu’on peut s’attendre pour toute prescription  ….  Mais la référence du prescripteur pourrait évoluer :
a.	L’INAMI pensait adapter le  N°INAMI pour qu’il ne contiennent plus de contenu.  (Qualification, etc.  => surlesquels des contrôles sont appliqués par rapport à certaines pathologies)
b.	Pourquoi ne pas penser qu’à termes ce soit certaines institutions qui soient responsable et qui puissent prescrire certaines choses

Ne pas communiquer de pdf quand on travaille avec UMEHP me parait de toute façon logique, car si la prescription est électronnique par défaut il n’y a pas de pdf. Donc la question qu’on avait tranché la dernière fois concernait les autres champs.

Voilà ce que je pense .. Et j’aurais aimé avoir ton avis …

Rem finale …  D’un point de vue pratique et pragmatique, je comprend le souhait que ces informations soient communiquées dans le message.  Cela évite dans un premier temps de devoir développer une interface UMEHP et cela évite potentiellement une surcharge d’appel vers UMEHP.  Mais cela implique un processus de qualité et de confiance de bout en bout car nous sommes en fin de chaîne et cela implique que toutes les informations structurées de la prescription nécessaires soient communiquées (Et ce n’est pas le cas).  

Bien à vous/Met vriendelijke Groeten/Kind regards

François Van Hees

**Comment by KarlienHL7Belgium** [comment]
goal is to discuss this and resolve in the WG meeting of 6 Dec

**Comment by bdc-ehealth** [comment]
WG: we discussed this with Francois, Bruno et Philippe, and the majority of the people did not have any objections against the presence of the fields.
